CREATE TABLE growth_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  client_name TEXT NOT NULL,
  coach_name TEXT NOT NULL,
  session_number TEXT,
  session_date DATE NOT NULL,
  coaching_type TEXT,
  conn_self_score INTEGER,
  conn_self_note TEXT,
  conn_child_score INTEGER,
  conn_child_note TEXT,
  awareness_text TEXT,
  awareness_score INTEGER,
  impl_tools TEXT,
  impl_notes TEXT,
  impl_score INTEGER,
  grow_where TEXT,
  grow_signs TEXT,
  grow_score INTEGER,
  concern_level TEXT,
  client_signals TEXT[],
  coach_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
