-- Add KPI-related columns to csm_daily_activity
ALTER TABLE csm_daily_activity
ADD COLUMN IF NOT EXISTS at_risk_identified INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS follow_ups_due INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS hours_worked NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS fte NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_max_workload INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_due_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_completed_today INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_carried_over INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tasks_overdue INTEGER DEFAULT 0;
